# Generated by Django 3.0.2 on 2020-07-27 07:30

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('eav', '0003_add_values_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='enumvalue',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='enumvalue',
            unique_together={('legacy_value', 'slug')},
        ),
    ]
